### Day 1 includes
> -  Preprocessing
> -  Simple Linear Regression
> -  Multiple Linear Regression
> -  Logistic Regression 
> -  Implementing Logistic Regression

### 1. Preprocessing

1.1 import packages

In [1]:
import numpy as np
import pandas as pd
print("Numpy version: ",np.__version__)
print("Pandas version: ",pd.__version__)

Numpy version:  1.19.0
Pandas version:  1.0.5


1.2 load the dataset 

In [2]:
dataset = pd.read_csv('Data.csv')

In [3]:
dataset

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

df.loc and df.iloc are used for indexing, i.e., to pull out portions of data. In essence, the difference is that .loc allows label-based indexing, while .iloc allows position-based indexing.

In [18]:
#dataset.select_dtypes(['object']).columns
fs = dataset.select_dtypes(['float']).columns

In [8]:
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, 3].values

In [9]:
X[:, 1:3]

array([[44.0, 72000.0],
       [27.0, 48000.0],
       [30.0, 54000.0],
       [38.0, 61000.0],
       [40.0, nan],
       [35.0, 58000.0],
       [nan, 52000.0],
       [48.0, 79000.0],
       [50.0, 83000.0],
       [37.0, 67000.0]], dtype=object)

1.3 handling the missing data 

In [143]:
#from sklearn.impute import SimpleImputer
#imputer = SimpleImputer(missing_values=np.nan, strategy="mean")
#imputer = imputer.fit(X[:, 1:3])
#X[:, 1:3] = imputer.transform(X[:, 1:3])

In [10]:
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, nan],
       ['France', 35.0, 58000.0],
       ['Spain', nan, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

1.4 Encoding categorical data

Categorical data are variables that contains label values rather than numarical values.
For example hair color, country, letter grade and so on.
There are actually two types of categorical data: 1. categorical and ordinal 2. categorical and nominal
1. <b>Categorical and ordinal</b> varialbles refer to categorical data if there is a logical ordering to the values of categorical data, e.g., letter grades.
2. <b>Categorical and nomial</b> variables refer to categorical data when there is no logical ordering to the values of categorical data, e.g., hair color. 

What is the problem with Categorical data?

Many machine learning algorithms cannot operate on label data directly. They require all input variables and output variables to be numeric.

In general, this is mostly a constraint of the efficient implementation of machine learning algorithms rather than hard limitations on the algorithms themselves.

but some algorithms can work directly on categorical data, e.g, decision tree.


for categorical and nominal variables we use <b>one hot encoding</b>






ordinal encoding is a natural encoding for ordinal variables. For categorical and nominal variables, it imposes an ordinal relationship where no such relationship may exist. This can cause problems and a one-hot encoding may be used instead.

Forcing an ordinal relationship via an ordinal encoding and allowing the model to assume a natural ordering between categories may result in poor performance or unexpected results (predictions halfway between categories).

In [51]:
from sklearn.preprocessing import OneHotEncoder, LabelEncoder
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
onehotencoder = OneHotEncoder()
ct = ColumnTransformer([('onehot', OneHotEncoder(), [0]),
                       ('imputer', SimpleImputer(missing_values=np.nan, strategy="mean"), fs)], remainder='passthrough')














#### sklearn.compose.ColumnTransformer

Applies transformers to columns of an array or pandas DataFrame.

In [52]:
encoded_X = ct.fit_transform(dataset)

In [53]:
encoded_X

array([[1.0, 0.0, 0.0, 44.0, 72000.0, 'No'],
       [0.0, 0.0, 1.0, 27.0, 48000.0, 'Yes'],
       [0.0, 1.0, 0.0, 30.0, 54000.0, 'No'],
       [0.0, 0.0, 1.0, 38.0, 61000.0, 'No'],
       [0.0, 1.0, 0.0, 40.0, 63777.77777777778, 'Yes'],
       [1.0, 0.0, 0.0, 35.0, 58000.0, 'Yes'],
       [0.0, 0.0, 1.0, 38.77777777777778, 52000.0, 'No'],
       [1.0, 0.0, 0.0, 48.0, 79000.0, 'Yes'],
       [0.0, 1.0, 0.0, 50.0, 83000.0, 'No'],
       [1.0, 0.0, 0.0, 37.0, 67000.0, 'Yes']], dtype=object)

In [38]:
labelencoder = LabelEncoder()
encodedd_X = labelencoder.fit_transform(encoded_X)

array([[1.0, 0.0, 0.0, 44.0, 72000.0, 'No'],
       [0.0, 0.0, 1.0, 27.0, 48000.0, 'Yes'],
       [0.0, 1.0, 0.0, 30.0, 54000.0, 'No'],
       [0.0, 0.0, 1.0, 38.0, 61000.0, 'No'],
       [0.0, 1.0, 0.0, 40.0, 63777.77777777778, 'Yes'],
       [1.0, 0.0, 0.0, 35.0, 58000.0, 'Yes'],
       [0.0, 0.0, 1.0, 38.77777777777778, 52000.0, 'No'],
       [1.0, 0.0, 0.0, 48.0, 79000.0, 'Yes'],
       [0.0, 1.0, 0.0, 50.0, 83000.0, 'No'],
       [1.0, 0.0, 0.0, 37.0, 67000.0, 'Yes']], dtype=object)

23

In [100]:
rX = onehotencoder.inverse_transform(en_X)

In [101]:
labelencoder_Y = LabelEncoder()
en_Y =  labelencoder_Y.fit_transform(y)

array([[0, 44.0, 72000.0],
       [2, 27.0, 48000.0],
       [1, 30.0, 54000.0],
       [2, 38.0, 61000.0],
       [1, 40.0, 63777.77777777778],
       [0, 35.0, 58000.0],
       [2, 38.77777777777778, 52000.0],
       [0, 48.0, 79000.0],
       [1, 50.0, 83000.0],
       [0, 37.0, 67000.0]], dtype=object)

In [59]:
le = LabelEncoder()
le.fit(["Berlin", "Paris", "Tokoyo", "Ameterdam"])

LabelEncoder()

In [60]:
le.classes_

array(['Ameterdam', 'Berlin', 'Paris', 'Tokoyo'], dtype='<U9')

In [65]:
encoded = le.transform(["Berlin", "Tokoyo", "Berlin", "Paris", "Paris"])

In [66]:
encoded

array([1, 3, 1, 2, 2])

In [69]:
decoded = le.inverse_transform(encoded);

In [70]:
decoded

array(['Berlin', 'Tokoyo', 'Berlin', 'Paris', 'Paris'], dtype='<U9')

In [ ]:
# We can also this process using Pandas's fillna method
df = dataset.fillna((dataset[['Age', 'Salary']]).mean())